services:
  api_express:
    container_name: api_kenzie_courses
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn migration:run && yarn dev'
  pg:
    container_name: db_courses
    image: postgres:latest
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
